object frm_AjudaComandos: Tfrm_AjudaComandos
  Left = 434
  Top = 18
  BorderIcons = [biSystemMenu]
  BorderStyle = bsNone
  ClientHeight = 511
  ClientWidth = 295
  Color = clInfoBk
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  OnActivate = FormActivate
  OnKeyDown = FormKeyDown
  PixelsPerInch = 96
  TextHeight = 13
  object Bevel1: TBevel
    Left = 0
    Top = 0
    Width = 295
    Height = 511
    Align = alClient
    Shape = bsFrame
  end
  object Bevel4: TBevel
    Left = 5
    Top = 4
    Width = 285
    Height = 502
    Shape = bsFrame
  end
  object Label2: TLabel
    Left = 119
    Top = 7
    Width = 65
    Height = 27
    Caption = 'Ajuda'
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -19
    Font.Name = 'Arial Black'
    Font.Style = [fsBold]
    ParentFont = False
    Transparent = True
  end
  object Bevel2: TBevel
    Left = 12
    Top = 458
    Width = 271
    Height = 10
    Shape = bsTopLine
  end
  object Bevel3: TBevel
    Left = 11
    Top = 31
    Width = 270
    Height = 9
    Shape = bsTopLine
  end
  object Panel2: TPanel
    Left = 12
    Top = 76
    Width = 239
    Height = 22
    Alignment = taLeftJustify
    BevelOuter = bvNone
    Color = clTeal
    Font.Charset = ANSI_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 0
  end
  object Panel6: TPanel
    Left = 12
    Top = 360
    Width = 266
    Height = 22
    Alignment = taLeftJustify
    BevelOuter = bvNone
    Color = clTeal
    Font.Charset = ANSI_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 1
  end
  object botao_sair: TPanel
    Left = 108
    Top = 469
    Width = 89
    Height = 23
    Cursor = crHandPoint
    BevelInner = bvRaised
    Caption = 'SAIR'
    Color = clRed
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 2
    OnClick = botao_sairClick
  end
  object btnFechar: TPanel
    Left = 257
    Top = 11
    Width = 23
    Height = 16
    Cursor = crHandPoint
    Caption = 'X'
    Color = clInfoBk
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 3
    OnClick = btnFecharClick
  end
  object Panel12: TPanel
    Left = 12
    Top = 217
    Width = 228
    Height = 22
    Alignment = taLeftJustify
    BevelOuter = bvNone
    Color = clTeal
    Font.Charset = ANSI_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 4
  end
  object Panel16: TPanel
    Left = 12
    Top = 279
    Width = 239
    Height = 22
    Alignment = taLeftJustify
    BevelOuter = bvNone
    Color = clTeal
    Font.Charset = ANSI_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 5
  end
  object Memo1: TMemo
    Left = 12
    Top = 54
    Width = 269
    Height = 393
    BorderStyle = bsNone
    Color = clInfoBk
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlack
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    Lines.Strings = (
      'Memo1')
    ParentFont = False
    ReadOnly = True
    TabOrder = 6
  end
end
