INSERT INTO CST_PIS (CODIGO, DESCRICAO) VALUES ('01', 'OPERACAO TRIBUTAVEL (BASE DE CALCULO=VALOR DA OPERACAO ALIQUOTA NORMAL (CUMULATIVO/NAO CUMULATIVO))');
INSERT INTO CST_PIS (CODIGO, DESCRICAO) VALUES ('02', 'OPERACAO TRIBUTAVEL (BASE DE CALCULO = VALOR DA OPERACAO (ALIQUOTA DIFERENCIDA)');
INSERT INTO CST_PIS (CODIGO, DESCRICAO) VALUES ('03', 'OPERACAO TRIBUTABEL (BASE DE CALCULO = QUANTIDADE VENDIDA X ALIQUOTA POR UNIDADE DO PRODUTO)');
INSERT INTO CST_PIS (CODIGO, DESCRICAO) VALUES ('04', 'OPERACAO TRIBUTAVEL (TRIBUTACAO MONOFASICA (ALIQUOTA ZERO))');
INSERT INTO CST_PIS (CODIGO, DESCRICAO) VALUES ('06', 'OPERACAO TRIBUTAVEL (ALIQUOTA ZERO)');
INSERT INTO CST_PIS (CODIGO, DESCRICAO) VALUES ('07', 'OPERACAO ISENTA DA CONTRIBUICAO');
INSERT INTO CST_PIS (CODIGO, DESCRICAO) VALUES ('08', 'OPERACAO SEM INCIDENCIA DA CONTRIBUICAO');
INSERT INTO CST_PIS (CODIGO, DESCRICAO) VALUES ('09', 'OPERACAO COM SUSPENSAO DA CONTRIBUICAO');
INSERT INTO CST_PIS (CODIGO, DESCRICAO) VALUES ('99', 'OUTRAS OPERACOES');

