INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1000', 'ENTRADAS OU AQUISIÇÕES DE SERVIÇOS DO ESTADO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1100', 'COMPRAS PARA INDUSTRIALIZAÇÃO, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1101', 'Compra para industrialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1102', 'Compra para comercialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1111', 'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1113', 'Compra para comercialização de mercadoria recebida anteriormente em consignação mercantil');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1116', 'Compra para industrialização originada de encomenda para recebimento futuro');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1117', 'Compra para comercialização originada de encomenda para recebimento futuro');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1118', 'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1120', 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1121', 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1122', 'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1124', 'Industrialização efetuada por outra empresa');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1125', 'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1126', 'Compra para utilização na prestação de serviço');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1150', 'TRANSFERÊNCIAS PARA INDUSTRIALIZAÇÃO, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1151', 'Transferência para industrialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1152', 'Transferência para comercialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1153', 'Transferência de energia elétrica para distribuição');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1154', 'Transferência para utilização na prestação de serviço');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1200', 'DEVOLUÇÕES DE VENDAS DE PRODUÇÃO PRÓPRIA, DE TERCEIROS OU ANULAÇÕES DE VALORES');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1201', 'Devolução de venda de produção do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1203', 'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1204', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1205', 'Anulação de valor relativo à prestação de serviço de comunicação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1206', 'Anulação de valor relativo à prestação de serviço de transporte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1207', 'Anulação de valor relativo à venda de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1208', 'Devolução de produção do estabelecimento, remetida em transferência');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1209', 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1250', 'COMPRAS DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1251', 'Compra de energia elétrica para distribuição ou comercialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1252', 'Compra de energia elétrica por estabelecimento industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1253', 'Compra de energia elétrica por estabelecimento comercial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1254', 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1255', 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1256', 'Compra de energia elétrica por estabelecimento de produtor rural');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1257', 'Compra de energia elétrica para consumo por demanda contratada');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1300', 'AQUISIÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1301', 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1302', 'Aquisição de serviço de comunicação por estabelecimento industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1303', 'Aquisição de serviço de comunicação por estabelecimento comercial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1304', 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1305', 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1306', 'Aquisição de serviço de comunicação por estabelecimento de produtor rural');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1350', 'AQUISIÇÕES DE SERVIÇOS DE TRANSPORTE');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1351', 'Aquisição de serviço de transporte para execução de serviço da mesma natureza');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1352', 'Aquisição de serviço de transporte por estabelecimento industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1353', 'Aquisição de serviço de transporte por estabelecimento comercial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1354', 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1355', 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1356', 'Aquisição de serviço de transporte por estabelecimento de produtor rural');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1400', 'ENTRADAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1401', 'Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1403', 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1406', 'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1407', 'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1408', 'Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1409', 'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1410', 'Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1411', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1414', 'Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1415', 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1450', 'SISTEMAS DE INTEGRAÇÃO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1451', 'Retorno de animal do estabelecimento produtor');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1452', 'Retorno de insumo não utilizado na produção');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1500', 'ENTRADAS DE MERCADORIAS REMETIDAS COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1501', 'Entrada de mercadoria recebida com fim específico de exportação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1503', 'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1504', 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1551', 'Compra de bem para o ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1552', 'Transferência de bem do ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1553', 'Devolução de venda de bem do ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1554', 'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1555', 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1556', 'Compra de material para uso ou consumo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1557', 'Transferência de material para uso ou consumo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1600', 'CRÉDITOS E RESSARCIMENTOS DE ICMS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1601', 'Recebimento, por transferência, de crédito de ICMS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1602', 'Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento da mesma empresa, para compensação de saldo devedor de ICMS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1603', 'Ressarcimento de ICMS retido por substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1900', 'OUTRAS ENTRADAS DE MERCADORIAS OU AQUISIÇÕES DE SERVIÇOS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1901', 'Entrada para industrialização por encomenda');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1902', 'Retorno de mercadoria remetida para industrialização por encomenda');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1903', 'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1904', 'Retorno de remessa para venda fora do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1905', 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1906', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1907', 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1908', 'Entrada de bem por conta de contrato de comodato');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1909', 'Retorno de bem remetido por conta de contrato de comodato');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1910', 'Entrada de bonificação, doação ou brinde');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1911', 'Entrada de amostra grátis');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1912', 'Entrada de mercadoria ou bem recebido para demonstração');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1913', 'Retorno de mercadoria ou bem remetido para demonstração');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1914', 'Retorno de mercadoria ou bem remetido para exposição ou feira');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1915', 'Entrada de mercadoria ou bem recebido para conserto ou reparo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1916', 'Retorno de mercadoria ou bem remetido para conserto ou reparo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1917', 'Entrada de mercadoria recebida em consignação mercantil ou industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1918', 'Devolução de mercadoria remetida em consignação mercantil ou industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1920', 'Entrada de vasilhame ou sacaria');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1921', 'Retorno de vasilhame ou sacaria');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1922', 'Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1923', 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1924', 'Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1925', 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1926', 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('1949', 'Outra entrada de mercadoria ou prestação de serviço não especificada');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2000', 'ENTRADAS OU AQUISIÇÕES DE SERVIÇOS DE OUTROS ESTADOS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2100', 'COMPRAS PARA INDUSTRIALIZAÇÃO, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2101', 'Compra para industrialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2102', 'Compra para comercialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2111', 'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2113', 'Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2116', 'Compra para industrialização originada de encomenda para recebimento futuro');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2117', 'Compra para comercialização originada de encomenda para recebimento futuro');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2118', 'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2120', 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2121', 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2122', 'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2124', 'Industrialização efetuada por outra empresa');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2125', 'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2126', 'Compra para utilização na prestação de serviço');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2150', 'TRANSFERÊNCIAS PARA INDUSTRIALIZAÇÃO, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2151', 'Transferência para industrialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2152', 'Transferência para comercialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2153', 'Transferência de energia elétrica para distribuição');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2154', 'Transferência para utilização na prestação de serviço');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2200', 'DEVOLUÇÕES DE VENDAS DE PRODUÇÃO PRÓPRIA, DE TERCEIROS OU ANULAÇÕES DE VALORES');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2201', 'Devolução de venda de produção do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2203', 'Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2204', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2205', 'Anulação de valor relativo à prestação de serviço de comunicação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2206', 'Anulação de valor relativo à prestação de serviço de transporte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2207', 'Anulação de valor relativo à venda de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2208', 'Devolução de produção do estabelecimento, remetida em transferência');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2209', 'Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2250', 'COMPRAS DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2251', 'Compra de energia elétrica para distribuição ou comercialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2252', 'Compra de energia elétrica por estabelecimento industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2253', 'Compra de energia elétrica por estabelecimento comercial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2254', 'Compra de energia elétrica por estabelecimento prestador de serviço de transporte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2255', 'Compra de energia elétrica por estabelecimento prestador de serviço de comunicação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2256', 'Compra de energia elétrica por estabelecimento de produtor rural');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2257', 'Compra de energia elétrica para consumo por demanda contratada');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2300', 'AQUISIÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2301', 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2302', 'Aquisição de serviço de comunicação por estabelecimento industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2303', 'Aquisição de serviço de comunicação por estabelecimento comercial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2304', 'Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2305', 'Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2306', 'Aquisição de serviço de comunicação por estabelecimento de produtor rural');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2350', 'AQUISIÇÕES DE SERVIÇOS DE TRANSPORTE');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2351', 'Aquisição de serviço de transporte para execução de serviço da mesma natureza');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2352', 'Aquisição de serviço de transporte por estabelecimento industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2353', 'Aquisição de serviço de transporte por estabelecimento comercial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2354', 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2355', 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2356', 'Aquisição de serviço de transporte por estabelecimento de produtor rural');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2400', 'ENTRADAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2401', 'Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2403', 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2406', 'Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2407', 'Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2408', 'Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2409', 'Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2410', 'Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2411', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2414', 'Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2415', 'Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2500', 'ENTRADAS DE MERCADORIAS REMETIDAS COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2501', 'Entrada de mercadoria recebida com fim específico de exportação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2503', 'Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2504', 'Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2551', 'Compra de bem para o ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2552', 'Transferência de bem do ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2553', 'Devolução de venda de bem do ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2554', 'Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2555', 'Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2556', 'Compra de material para uso ou consumo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2557', 'Transferência de material para uso ou consumo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2600', 'CRÉDITOS E RESSARCIMENTOS DE ICMS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2603', 'Ressarcimento de ICMS retido por substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2900', 'OUTRAS ENTRADAS DE MERCADORIAS OU AQUISIÇÕES DE SERVIÇOS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2901', 'Entrada para industrialização por encomenda');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2902', 'Retorno de mercadoria remetida para industrialização por encomenda');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2903', 'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2904', 'Retorno de remessa para venda fora do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2905', 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2906', 'Retorno de mercadoria remetida para depósito fechado ou armazém geral');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2907', 'Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2908', 'Entrada de bem por conta de contrato de comodato');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2909', 'Retorno de bem remetido por conta de contrato de comodato');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2910', 'Entrada de bonificação, doação ou brinde');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2911', 'Entrada de amostra grátis');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2912', 'Entrada de mercadoria ou bem recebido para demonstração');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2913', 'Retorno de mercadoria ou bem remetido para demonstração');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2914', 'Retorno de mercadoria ou bem remetido para exposição ou feira');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2915', 'Entrada de mercadoria ou bem recebido para conserto ou reparo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2916', 'Retorno de mercadoria ou bem remetido para conserto ou reparo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2917', 'Entrada de mercadoria recebida em consignação mercantil ou industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2918', 'Devolução de mercadoria remetida em consignação mercantil ou industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2920', 'Entrada de vasilhame ou sacaria');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2921', 'Retorno de vasilhame ou sacaria');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2922', 'Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2923', 'Entrada de mercadoria recebida do vendedor remetente, em venda à ordem');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2924', 'Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2925', 'Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('2949', 'Outra entrada de mercadoria ou prestação de serviço não especificado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3000', 'ENTRADAS OU AQUISIÇÕES DE SERVIÇOS DO EXTERIOR');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3100', 'COMPRAS PARA INDUSTRIALIZAÇÃO, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3101', 'Compra para industrialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3102', 'Compra para comercialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3126', 'Compra para utilização na prestação de serviço');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3127', 'Compra para industrialização sob o regime de “drawback”');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3200', 'DEVOLUÇÕES DE VENDAS DE PRODUÇÃO PRÓPRIA, DE TERCEIROS OU ANULAÇÕES DE VALORES');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3201', 'Devolução de venda de produção do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3202', 'Devolução de venda de mercadoria adquirida ou recebida de terceiros');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3205', 'Anulação de valor relativo à prestação de serviço de comunicação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3206', 'Anulação de valor relativo à prestação de serviço de transporte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3207', 'Anulação de valor relativo à venda de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3211', 'Devolução de venda de produção do estabelecimento sob o regime de “drawback”');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3250', 'COMPRAS DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3251', 'Compra de energia elétrica para distribuição ou comercialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3300', 'AQUISIÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3301', 'Aquisição de serviço de comunicação para execução de serviço da mesma natureza');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3350', 'AQUISIÇÕES DE SERVIÇOS DE TRANSPORTE');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3351', 'Aquisição de serviço de transporte para execução de serviço da mesma natureza');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3352', 'Aquisição de serviço de transporte por estabelecimento industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3353', 'Aquisição de serviço de transporte por estabelecimento comercial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3354', 'Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3355', 'Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3356', 'Aquisição de serviço de transporte por estabelecimento de produtor rural');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3500', 'ENTRADAS DE MERCADORIAS REMETIDAS COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3503', 'Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3551', 'Compra de bem para o ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3553', 'Devolução de venda de bem do ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3556', 'Compra de material para uso ou consumo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3900', 'OUTRAS ENTRADAS DE MERCADORIAS OU AQUISIÇÕES DE SERVIÇOS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3930', 'Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('3949', 'Outra entrada de mercadoria ou prestação de serviço não especificado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5000', 'SAÍDAS OU PRESTAÇÕES DE SERVIÇOS PARA O ESTADO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5100', 'VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5101', 'Venda de produção do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5102', 'Venda Merc.Adq.ou Receb.Terceiros');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5103', 'Venda de produção do estabelecimento, efetuada fora do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5104', 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5105', 'Venda de produção do estabelecimento que não deva por ele transitar');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5106', 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5109', 'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5110', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5111', 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5112', 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5113', 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5114', 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5115', 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5116', 'Venda de produção do estabelecimento originada de encomenda para entrega futura');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5117', 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5118', 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5119', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5120', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5122', 'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5123', 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5124', 'Industrialização efetuada para outra empresa');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5125', 'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5150', 'TRANSFERÊNCIAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5151', 'Transferência de produção do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5152', 'Transferência de mercadoria adquirida ou recebida de terceiros');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5153', 'Transferência de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5155', 'Transferência de produção do estabelecimento, que não deva por ele transitar');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5156', 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5200', 'DEVOLUÇÕES DE COMPRAS PARA INDUSTRIALIZAÇÃO, COMERCIALIZAÇÃO OU ANULAÇÕES DE VALORES');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5201', 'Devolução de compra para industrialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5202', 'Devolução de compra para comercialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5205', 'Anulação de valor relativo a aquisição de serviço de comunicação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5206', 'Anulação de valor relativo a aquisição de serviço de transporte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5207', 'Anulação de valor relativo à compra de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5208', 'Devolução de mercadoria recebida em transferência para industrialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5209', 'Devolução de mercadoria recebida em transferência para comercialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5210', 'Devolução de compra para utilização na prestação de serviço');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5250', 'VENDAS DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5251', 'Venda de energia elétrica para distribuição ou comercialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5252', 'Venda de energia elétrica para estabelecimento industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5253', 'Venda de energia elétrica para estabelecimento comercial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5254', 'Venda de energia elétrica para estabelecimento prestador de serviço de transporte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5255', 'Venda de energia elétrica para estabelecimento prestador de serviço de comunicação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5256', 'Venda de energia elétrica para estabelecimento de produtor rural');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5257', 'Venda de energia elétrica para consumo por demanda contratada');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5258', 'Venda de energia elétrica a não-contribuinte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5300', 'PRESTAÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5301', 'Prestação de serviço de comunicação para execução de serviço da mesma natureza');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5302', 'Prestação de serviço de comunicação a estabelecimento industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5303', 'Prestação de serviço de comunicação a estabelecimento comercial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5304', 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5305', 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5306', 'Prestação de serviço de comunicação a estabelecimento de produtor rural');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5307', 'Prestação de serviço de comunicação a não-contribuinte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5350', 'PRESTAÇÕES DE SERVIÇOS DE TRANSPORTE');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5351', 'Prestação de serviço de transporte para execução de serviço da mesma natureza');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5352', 'Prestação de serviço de transporte a estabelecimento industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5353', 'Prestação de serviço de transporte a estabelecimento comercial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5354', 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5355', 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5356', 'Prestação de serviço de transporte a estabelecimento de produtor rural');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5357', 'Prestação de serviço de transporte a não-contribuinte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5400', 'SAÍDAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5401', 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5402', 'Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5403', 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5405', 'Venda Merc.Adq.C/Subst.Tributária C/Contr.Substituído');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5408', 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5409', 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5410', 'Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5411', 'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5412', 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5413', 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5414', 'Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5415', 'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5450', 'SISTEMAS DE INTEGRAÇÃO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5451', 'Remessa de animal e de insumo para estabelecimento produtor');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5500', 'REMESSAS COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5501', 'Remessa de produção do estabelecimento, com fim específico de exportação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5502', 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5503', 'Devolução de mercadoria recebida com fim específico de exportação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5551', 'Venda de bem do ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5552', 'Transferência de bem do ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5553', 'Devolução de compra de bem para o ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5554', 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5555', 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5556', 'Devolução de compra de material de uso ou consumo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5557', 'Transferência de material de uso ou consumo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5600', 'CRÉDITOS E RESSARCIMENTOS DE ICMS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5601', 'Transferência de crédito de ICMS acumulado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5602', 'Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5603', 'Ressarcimento de ICMS retido por substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5900', 'OUTRAS SAÍDAS DE MERCADORIAS OU PRESTAÇÕES DE SERVIÇOS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5901', 'Remessa para industrialização por encomenda');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5902', 'Retorno de mercadoria utilizada na industrialização por encomenda');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5903', 'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5904', 'Remessa para venda fora do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5905', 'Remessa para depósito fechado ou armazém geral');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5906', 'Retorno de mercadoria depositada em depósito fechado ou armazém geral');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5907', 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5908', 'Remessa de bem por conta de contrato de comodato');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5909', 'Retorno de bem recebido por conta de contrato de comodato');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5910', 'Remessa em bonificação, doação ou brinde');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5911', 'Remessa de amostra grátis');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5912', 'Remessa de mercadoria ou bem para demonstração');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5913', 'Retorno de mercadoria ou bem recebido para demonstração');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5914', 'Remessa de mercadoria ou bem para exposição ou feira');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5915', 'Remessa de mercadoria ou bem para conserto ou reparo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5916', 'Retorno de mercadoria ou bem recebido para conserto ou reparo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5917', 'Remessa de mercadoria em consignação mercantil ou industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5918', 'Devolução de mercadoria recebida em consignação mercantil ou industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5920', 'Remessa de vasilhame ou sacaria');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5921', 'Devolução de vasilhame ou sacaria');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5922', 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5923', 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5924', 'Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5925', 'Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5926', 'Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5927', 'Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5928', 'Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5929', 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5931', 'Lançamento efetuado em decorrência da respons. de retenção do imposto por subst. tributária, atribuída ao rem. ou alienante da merc., pelo serv. de transp. realizado por transp. autônomo ou por transp. não inscrito na UF onde iniciado o serviço');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5932', 'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('5949', 'Outra saída de mercadoria ou prestação de serviço não especificado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6000', 'SAÍDAS OU PRESTAÇÕES DE SERVIÇOS PARA OUTROS ESTADOS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6100', 'VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6101', 'Venda de produção do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6102', 'Venda Merc.Adq.ou Receb.Terceiros');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6103', 'Venda de produção do estabelecimento, efetuada fora do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6104', 'Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6105', 'Venda de produção do estabelecimento que não deva por ele transitar');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6106', 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6107', 'Venda de produção do estabelecimento, destinada a não-contribuinte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6108', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada a não-contribuinte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6109', 'Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6110', 'Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6111', 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6112', 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6113', 'Venda de produção do estabelecimento remetida anteriormente em consignação mercantil');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6114', 'Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6115', 'Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6116', 'Venda de produção do estabelecimento originada de encomenda para entrega futura');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6117', 'Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6118', 'Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6119', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6120', 'Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6122', 'Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6123', 'Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6124', 'Industrialização efetuada para outra empresa');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6125', 'Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6150', 'TRANSFERÊNCIAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6151', 'Transferência de produção do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6152', 'Transferência de mercadoria adquirida ou recebida de terceiros');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6153', 'Transferência de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6155', 'Transferência de produção do estabelecimento, que não deva por ele transitar');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6156', 'Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6200', 'DEVOLUÇÕES DE COMPRAS PARA INDUSTRIALIZAÇÃO, COMERCIALIZAÇÃO OU ANULAÇÕES DE VALORES');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6201', 'Devolução de compra para industrialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6202', 'Devolução de compra para comercialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6205', 'Anulação de valor relativo a aquisição de serviço de comunicação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6206', 'Anulação de valor relativo a aquisição de serviço de transporte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6207', 'Anulação de valor relativo à compra de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6208', 'Devolução de mercadoria recebida em transferência para industrialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6209', 'Devolução de mercadoria recebida em transferência para comercialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6210', 'Devolução de compra para utilização na prestação de serviço');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6250', 'VENDAS DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6251', 'Venda de energia elétrica para distribuição ou comercialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6252', 'Venda de energia elétrica para estabelecimento industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6253', 'Venda de energia elétrica para estabelecimento comercial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6254', 'Venda de energia elétrica para estabelecimento prestador de serviço de transporte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6255', 'Venda de energia elétrica para estabelecimento prestador de serviço de comunicação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6256', 'Venda de energia elétrica para estabelecimento de produtor rural');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6257', 'Venda de energia elétrica para consumo por demanda contratada');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6258', 'Venda de energia elétrica a não-contribuinte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6300', 'PRESTAÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6301', 'Prestação de serviço de comunicação para execução de serviço da mesma natureza');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6302', 'Prestação de serviço de comunicação a estabelecimento industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6303', 'Prestação de serviço de comunicação a estabelecimento comercial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6304', 'Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6305', 'Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6306', 'Prestação de serviço de comunicação a estabelecimento de produtor rural');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6307', 'Prestação de serviço de comunicação a não-contribuinte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6350', 'PRESTAÇÕES DE SERVIÇOS DE TRANSPORTE');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6351', 'Prestação de serviço de transporte para execução de serviço da mesma natureza');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6352', 'Prestação de serviço de transporte a estabelecimento industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6353', 'Prestação de serviço de transporte a estabelecimento comercial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6354', 'Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6355', 'Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6356', 'Prestação de serviço de transporte a estabelecimento de produtor rural');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6357', 'Prestação de serviço de transporte a não-contribuinte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6400', 'SAÍDAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6401', 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6402', 'Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6403', 'Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6404', 'Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6408', 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6409', 'Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6410', 'Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6411', 'Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6412', 'Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6413', 'Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6414', 'Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6415', 'Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6500', 'REMESSAS COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6501', 'Remessa de produção do estabelecimento, com fim específico de exportação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6502', 'Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6503', 'Devolução de mercadoria recebida com fim específico de exportação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6551', 'Venda de bem do ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6552', 'Transferência de bem do ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6553', 'Devolução de compra de bem para o ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6554', 'Remessa de bem do ativo imobilizado para uso fora do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6555', 'Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6556', 'Devolução de compra de material de uso ou consumo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6557', 'Transferência de material de uso ou consumo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6600', 'CRÉDITOS E RESSARCIMENTOS DE ICMS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6603', 'Ressarcimento de ICMS retido por substituição tributária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6900', 'OUTRAS SAÍDAS DE MERCADORIAS OU PRESTAÇÕES DE SERVIÇOS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6901', 'Remessa para industrialização por encomenda');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6902', 'Retorno de mercadoria utilizada na industrialização por encomenda');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6903', 'Retorno de mercadoria recebida para industrialização e não aplicada no referido processo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6904', 'Remessa para venda fora do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6905', 'Remessa para depósito fechado ou armazém geral');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6906', 'Retorno de mercadoria depositada em depósito fechado ou armazém geral');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6907', 'Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6908', 'Remessa de bem por conta de contrato de comodato');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6909', 'Retorno de bem recebido por conta de contrato de comodato');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6910', 'Remessa em bonificação, doação ou brinde');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6911', 'Remessa de amostra grátis');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6912', 'Remessa de mercadoria ou bem para demonstração');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6913', 'Retorno de mercadoria ou bem recebido para demonstração');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6914', 'Remessa de mercadoria ou bem para exposição ou feira');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6915', 'Remessa de mercadoria ou bem para conserto ou reparo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6916', 'Retorno de mercadoria ou bem recebido para conserto ou reparo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6917', 'Remessa de mercadoria em consignação mercantil ou industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6918', 'Devolução de mercadoria recebida em consignação mercantil ou industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6919', 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6920', 'Remessa de vasilhame ou sacaria');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6921', 'Devolução de vasilhame ou sacaria');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6922', 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6923', 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6924', 'Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6925', 'Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6929', 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal - ECF');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6931', 'Lançamento efetuado em decorrência da respons. de retenção do imposto por subst. tributária, atribuída ao rem. ou alienante da merc., pelo serv. de transp. realizado por transp. autônomo ou por transp. não inscrito na UF onde iniciado o serviço');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6932', 'Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('6949', 'Outra saída de mercadoria ou prestação de serviço não especificado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7000', 'SAÍDAS OU PRESTAÇÕES DE SERVIÇOS PARA O EXTERIOR');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7100', 'VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS');
COMMIT WORK;
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7101', 'Venda de produção do estabelecimento');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7102', 'Venda de mercadoria adquirida ou recebida de terceiros');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7105', 'Venda de produção do estabelecimento, que não deva por ele transitar');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7106', 'Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7127', 'Venda de produção do estabelecimento sob o regime de “drawback”');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7200', 'DEVOLUÇÕES DE COMPRAS PARA INDUSTRIALIZAÇÃO, COMERCIALIZAÇÃO OU ANULAÇÕES DE VALORES');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7201', 'Devolução de compra para industrialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7202', 'Devolução de compra para comercialização');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7205', 'Anulação de valor relativo à aquisição de serviço de comunicação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7206', 'Anulação de valor relativo a aquisição de serviço de transporte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7207', 'Anulação de valor relativo à compra de energia elétrica');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7210', 'Devolução de compra para utilização na prestação de serviço');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7211', 'Devolução de compras para industrialização sob o regime de “drawback”');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7250', 'VENDAS DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7251', 'Venda de energia elétrica para o exterior');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7300', 'PRESTAÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7301', 'Prestação de serviço de comunicação para execução de serviço da mesma natureza');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7350', 'PRESTAÇÕES DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7358', 'Prestação de serviço de transporte');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7500', 'EXPORTAÇÃO DE MERCADORIAS RECEBIDAS COM FIM ESPECÍFICO DE EXPORTAÇÃO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7501', 'Exportação de mercadorias recebidas com fim específico de exportação');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7551', 'Venda de bem do ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7553', 'Devolução de compra de bem para o ativo imobilizado');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7556', 'Devolução de compra de material de uso ou consumo');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7900', 'OUTRAS SAÍDAS DE MERCADORIAS OU PRESTAÇÕES DE SERVIÇOS');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7930', 'Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária');
INSERT INTO CFOP (CFOP, DESCRICAO) VALUES ('7949', 'Outra saída de mercadoria ou prestação de serviço não especificado');

