INSERT INTO CST_IPI (CODIGO, DESCRICAO) VALUES ('00', 'ENTRADA COM RECUPERAÇÃO DE CREDITO');
INSERT INTO CST_IPI (CODIGO, DESCRICAO) VALUES ('01', 'ENTRADA TRIBUTADA COM ALIQUOTA ZERO');
INSERT INTO CST_IPI (CODIGO, DESCRICAO) VALUES ('02', 'ENTRADA ISENTA');
INSERT INTO CST_IPI (CODIGO, DESCRICAO) VALUES ('03', 'ENTRADA NAO-TRIBUTADA');
INSERT INTO CST_IPI (CODIGO, DESCRICAO) VALUES ('04', 'ENTRADA IMUNE');
INSERT INTO CST_IPI (CODIGO, DESCRICAO) VALUES ('05', 'ENTRADA COM SUSPENSAO');
INSERT INTO CST_IPI (CODIGO, DESCRICAO) VALUES ('49', 'OUTRAS ENTRADAS');
INSERT INTO CST_IPI (CODIGO, DESCRICAO) VALUES ('50', 'SAIDA TRIBUTADA');
INSERT INTO CST_IPI (CODIGO, DESCRICAO) VALUES ('51', 'SAIDA TRIBUTADA COM ALIQUOTA ZERO');
INSERT INTO CST_IPI (CODIGO, DESCRICAO) VALUES ('52', 'SAIDA ISENTA');
INSERT INTO CST_IPI (CODIGO, DESCRICAO) VALUES ('53', 'SAIDA NAO-TRIBUTADA');
INSERT INTO CST_IPI (CODIGO, DESCRICAO) VALUES ('54', 'SAIDA IMUNE');
INSERT INTO CST_IPI (CODIGO, DESCRICAO) VALUES ('55', 'SAIDA COM SUSPENSAO');
INSERT INTO CST_IPI (CODIGO, DESCRICAO) VALUES ('99', 'OUTRAS SAIDAS');

