INSERT INTO CST_ICMS (CODIGO, DESCRICAO) VALUES ('00', 'TRIBUTADA INTEGRALMENTE');
INSERT INTO CST_ICMS (CODIGO, DESCRICAO) VALUES ('10', 'TRIBUTADA E COM COBRANCA DO ICMS POR SUBSTITUICAO TRIBUTARIA');
INSERT INTO CST_ICMS (CODIGO, DESCRICAO) VALUES ('20', 'COM REDUCAO DE BASE DE CALCULO');
INSERT INTO CST_ICMS (CODIGO, DESCRICAO) VALUES ('30', 'ISENTA OU NAO TRIBUTADA E COM COBRANCA DO ICMS POR SUBSTITUICAO TRIBUTARIA');
INSERT INTO CST_ICMS (CODIGO, DESCRICAO) VALUES ('40', 'ISENTA');
INSERT INTO CST_ICMS (CODIGO, DESCRICAO) VALUES ('41', 'NAO TRIBUTADA');
INSERT INTO CST_ICMS (CODIGO, DESCRICAO) VALUES ('50', 'SUSPENSAO');
INSERT INTO CST_ICMS (CODIGO, DESCRICAO) VALUES ('51', 'DIFERIMENTO');
INSERT INTO CST_ICMS (CODIGO, DESCRICAO) VALUES ('60', 'ICMS COBRADO ANTERIOMENTE POR SUBSTITUICAO TRIBUTARIA');
INSERT INTO CST_ICMS (CODIGO, DESCRICAO) VALUES ('70', 'COM REDUCAO DE BASE DE CALCULO E COBRANCA DO ICMS POR SUBSTITUICAO TRIBUTARIA');
INSERT INTO CST_ICMS (CODIGO, DESCRICAO) VALUES ('90', 'OUTROS');

